from .admin_funcs import *
from .info_about_protos import *
from .more_about_vpn import *
from .requests_access import *
from .send_configs import *
from .show_ovpn_proto import *
from .show_protos_menu import *
from .show_start_menu import *
from .show_vpn_info import *
from .instructions import *
from .show_vpn_variants_menu import *
from .main_menu import *
from .settings_menu import *
