from .admin_tools import *
from .info_about_protos import *
from .info_about_vpn import *
from .send_configs import *
from .protos_menu import *
from .start_handler import *
from .vpn_info_menu import *
from .instructions import *
from .vpn_variants_menu import *
from .main_menu import *
from .settings_menu import *
